import { FancyStyle } from './types';
import {
  transformBold,
  transformItalic,
  transformBoldItalic,
  transformScript,
  transformBoldScript,
  transformFraktur,
  transformBoldFraktur,
  transformDoubleStruck,
  transformSans,
  transformSansBold,
  transformSansItalic,
  transformSansBoldItalic,
  transformMonospace,
  transformSmallCaps,
  transformFullwidth,
  transformCircled,
  transformParenthesized,
  transformSquared,
  transformSuperscript,
  transformSubscript,
  transformBubble,
  transformStrikethrough,
  transformUnderline,
  transformSlash,
  transformReverse,
} from './transforms';

export const FANCY_STYLES: FancyStyle[] = [
  {
    id: 'bold',
    name: 'Bold',
    slug: 'bold-font-generator',
    description: 'Mathematical Bold Unicode Characters',
    category: 'popular',
    transform: transformBold,
    tags: ['bold', 'heavy', 'thick', 'strong', 'popular'],
  },
  {
    id: 'italic',
    name: 'Italic',
    slug: 'italic-font-generator',
    description: 'Mathematical Italic Slanted Characters',
    category: 'popular',
    transform: transformItalic,
    tags: ['italic', 'slanted', 'emphasis', 'popular'],
  },
  {
    id: 'bold-italic',
    name: 'Bold Italic',
    slug: 'bold-italic-font',
    description: 'Mathematical Bold & Slanted Unicode',
    category: 'popular',
    transform: transformBoldItalic,
    tags: ['bold', 'italic', 'heavy', 'slanted', 'popular'],
  },
  {
    id: 'script',
    name: 'Script / Cursive',
    slug: 'cursive-font-generator',
    description: 'Flowing Calligraphic Script Characters',
    category: 'popular',
    transform: transformScript,
    tags: ['script', 'cursive', 'handwriting', 'calligraphy', 'popular', 'instagram'],
  },
  {
    id: 'bold-script',
    name: 'Bold Script',
    slug: 'bold-script-font',
    description: 'Heavy Calligraphic Brush Script',
    category: 'popular',
    transform: transformBoldScript,
    tags: ['script', 'cursive', 'bold', 'brush', 'popular'],
  },
  {
    id: 'fraktur',
    name: 'Fraktur / Gothic',
    slug: 'gothic-font-generator',
    description: 'Classical German Fraktur & Old English Gothic',
    category: 'popular',
    transform: transformFraktur,
    tags: ['fraktur', 'gothic', 'old english', 'vintage', 'popular', 'discord'],
  },
  {
    id: 'bold-fraktur',
    name: 'Bold Fraktur',
    slug: 'bold-gothic-font',
    description: 'Heavy Old English & Dark Gothic Type',
    category: 'popular',
    transform: transformBoldFraktur,
    tags: ['fraktur', 'gothic', 'bold', 'dark', 'metal'],
  },
  {
    id: 'double-struck',
    name: 'Double Struck',
    slug: 'double-struck-font',
    description: 'Blackboard Bold & Outline Mathematical Symbols',
    category: 'decorative',
    transform: transformDoubleStruck,
    tags: ['double struck', 'blackboard', 'outline', 'math', 'decorative'],
  },
  {
    id: 'sans-serif',
    name: 'Sans Serif',
    slug: 'sans-serif-font',
    description: 'Clean Modern Sans Serif Unicode Text',
    category: 'popular',
    transform: transformSans,
    tags: ['sans', 'clean', 'modern', 'minimal'],
  },
  {
    id: 'sans-bold',
    name: 'Sans Serif Bold',
    slug: 'sans-bold-font',
    description: 'Heavy Modern Sans Serif Type',
    category: 'popular',
    transform: transformSansBold,
    tags: ['sans', 'bold', 'clean', 'modern'],
  },
  {
    id: 'sans-italic',
    name: 'Sans Serif Italic',
    slug: 'sans-italic-font',
    description: 'Clean Slanted Sans Serif',
    category: 'popular',
    transform: transformSansItalic,
    tags: ['sans', 'italic', 'slanted'],
  },
  {
    id: 'sans-bold-italic',
    name: 'Sans Serif Bold Italic',
    slug: 'sans-bold-italic-font',
    description: 'Heavy Slanted Modern Sans',
    category: 'popular',
    transform: transformSansBoldItalic,
    tags: ['sans', 'bold', 'italic'],
  },
  {
    id: 'monospace',
    name: 'Monospace',
    slug: 'monospace-font',
    description: 'Fixed-width Typewriter & Terminal Font',
    category: 'decorative',
    transform: transformMonospace,
    tags: ['monospace', 'code', 'terminal', 'typewriter', 'tech'],
  },
  {
    id: 'small-caps',
    name: 'Small Caps',
    slug: 'small-caps-font-generator',
    description: 'Compact Small Capital Letterforms',
    category: 'social',
    transform: transformSmallCaps,
    tags: ['small caps', 'mini caps', 'social', 'instagram', 'tiktok'],
  },
  {
    id: 'fullwidth',
    name: 'Fullwidth / Vaporwave',
    slug: 'aesthetic-font-generator',
    description: 'Wide Spaced Vaporwave Aesthetic Characters',
    category: 'social',
    transform: transformFullwidth,
    tags: ['fullwidth', 'vaporwave', 'aesthetic', 'wide', 'social'],
  },
  {
    id: 'circled',
    name: 'Circled',
    slug: 'circled-font',
    description: 'Enclosed Round Circled Letters & Numbers',
    category: 'decorative',
    transform: transformCircled,
    tags: ['circled', 'bubble', 'round', 'enclosed', 'decorative'],
  },
  {
    id: 'parenthesized',
    name: 'Parenthesized',
    slug: 'parenthesized-font',
    description: 'Characters Enclosed in Soft Parentheses',
    category: 'decorative',
    transform: transformParenthesized,
    tags: ['parentheses', 'enclosed', 'decorative'],
  },
  {
    id: 'squared',
    name: 'Squared',
    slug: 'squared-font',
    description: 'Enclosed Square Block Letterforms',
    category: 'decorative',
    transform: transformSquared,
    tags: ['squared', 'boxes', 'block', 'decorative'],
  },
  {
    id: 'superscript',
    name: 'Superscript',
    slug: 'superscript-font',
    description: 'Elevated High-Position Text & Digits',
    category: 'social',
    transform: transformSuperscript,
    tags: ['superscript', 'high', 'mini', 'social'],
  },
  {
    id: 'subscript',
    name: 'Subscript',
    slug: 'subscript-font',
    description: 'Lowered Base-Position Text & Digits',
    category: 'social',
    transform: transformSubscript,
    tags: ['subscript', 'low', 'mini', 'social'],
  },
  {
    id: 'bubble',
    name: 'Bubble (Dark)',
    slug: 'bubble-font-generator',
    description: 'Dark Filled Negative Circled Lettering',
    category: 'social',
    transform: transformBubble,
    tags: ['bubble', 'dark', 'filled', 'social', 'tiktok', 'discord'],
  },
  {
    id: 'strikethrough',
    name: 'Strikethrough',
    slug: 'strikethrough-font',
    description: 'Horizontal Line Across Every Character',
    category: 'social',
    transform: transformStrikethrough,
    tags: ['strikethrough', 'cross out', 'social', 'discord'],
  },
  {
    id: 'underline',
    name: 'Underline',
    slug: 'underline-font',
    description: 'Continuous Bottom Rule Accent',
    category: 'social',
    transform: transformUnderline,
    tags: ['underline', 'line', 'social'],
  },
  {
    id: 'slash',
    name: 'Slash Through',
    slug: 'slash-font',
    description: 'Diagonal Slash Accents Across Characters',
    category: 'decorative',
    transform: transformSlash,
    tags: ['slash', 'glitch', 'decorative'],
  },
  {
    id: 'reverse',
    name: 'Reverse / Mirrored',
    slug: 'reverse-font',
    description: 'Backwards and Upside-down Mirrored Characters',
    category: 'decorative',
    transform: transformReverse,
    tags: ['reverse', 'mirrored', 'backwards', 'upside down'],
  },
];
